let data={
    "menuTree": [
      {
        "menuId": "3197bf2e-79a3-4203-b907-ddd953becb38",
        "menuIcourl": "iconfont icon-management-fill",
        "menuText": "用户权限",
        "menuParentid": "",
        "menuLinkurl": null,
        "menuOtherparam": null,
        "menuLinktarget": "Tab",
        "menuType": "菜单",
        "menuIsdefault": "是",
        "menuIsmodify": "启用",
        "menuPos": "左侧",
        "menuCreateby": null,
        "menuCreatetime": 1530733502000,
        "menuSortnum": 10,
        "menuNote": null,
        "menuLinkname": null
      },
      {
        "menuId": "5be14f90-c45e-44ec-96b5-b7ef636dde96",
        "menuIcourl": "iconfont icon-organization",
        "menuText": "组织机构管理",
        "menuParentid": "3197bf2e-79a3-4203-b907-ddd953becb38",
        "menuLinkurl": "../frames/auth/orgTreeManager/index.html",
        "menuOtherparam": null,
        "menuLinktarget": "Tab",
        "menuType": "链接",
        "menuIsdefault": "是",
        "menuIsmodify": "启用",
        "menuPos": "左侧",
        "menuCreateby": null,
        "menuCreatetime": 1527017245000,
        "menuSortnum": 10,
        "menuNote": null,
        "menuLinkname": null
      },
      {
        "menuId": "1518223a-dd2a-4b5e-8315-145924966c8c",
        "menuIcourl": "iconfont icon-users",
        "menuText": "用户角色管理",
        "menuParentid": "3197bf2e-79a3-4203-b907-ddd953becb38",
        "menuLinkurl": "../frames/auth/roleManager/index.html",
        "menuOtherparam": null,
        "menuLinktarget": "Tab",
        "menuType": "链接",
        "menuIsdefault": "是",
        "menuIsmodify": "启用",
        "menuPos": "左侧",
        "menuCreateby": null,
        "menuCreatetime": 1527277514000,
        "menuSortnum": 20,
        "menuNote": "角色管理",
        "menuLinkname": null
      },
      {
        "menuId": "d5d2eeee-1e5b-484c-944a-57b4fa0fe285",
        "menuIcourl": "iconfont icon-functional-authority",
        "menuText": "功能权限管理",
        "menuParentid": "3197bf2e-79a3-4203-b907-ddd953becb38",
        "menuLinkurl": "../frames/auth/authManager/index.html",
        "menuOtherparam": null,
        "menuLinktarget": "Tab",
        "menuType": "链接",
        "menuIsdefault": "是",
        "menuIsmodify": "启用",
        "menuPos": "左侧",
        "menuCreateby": null,
        "menuCreatetime": 1527017328000,
        "menuSortnum": 30,
        "menuNote": null,
        "menuLinkname": null
      },
      {
        "menuId": "5498ac00-1826-4d03-9ca2-b831ca8f4a66",
        "menuIcourl": "iconfont icon-personnel-report",
        "menuText": "人员权限查询",
        "menuParentid": "3197bf2e-79a3-4203-b907-ddd953becb38",
        "menuLinkurl": "../frames/auth/authByUserQuery/index.html",
        "menuOtherparam": null,
        "menuLinktarget": "Tab",
        "menuType": "链接",
        "menuIsdefault": "是",
        "menuIsmodify": "启用",
        "menuPos": "左侧",
        "menuCreateby": null,
        "menuCreatetime": 1527295714000,
        "menuSortnum": 40,
        "menuNote": null,
        "menuLinkname": null
      },
      {
        "menuId": "c5ee0a95-b8a7-41e3-a596-6b6f2e412146",
        "menuIcourl": "iconfont icon-personnel-query",
        "menuText": "权限人员查询",
        "menuParentid": "3197bf2e-79a3-4203-b907-ddd953becb38",
        "menuLinkurl": "../frames/auth/userByAuthQuery/index.html",
        "menuOtherparam": null,
        "menuLinktarget": "Tab",
        "menuType": "链接",
        "menuIsdefault": "是",
        "menuIsmodify": "启用",
        "menuPos": "左侧",
        "menuCreateby": null,
        "menuCreatetime": 1527295687000,
        "menuSortnum": 50,
        "menuNote": null,
        "menuLinkname": null
      },
      {
        "menuId": "113a4964-f650-4283-b665-a9fe284cb77e",
        "menuIcourl": "iconfont icon-phoneboo",
        "menuText": "用户操作日志",
        "menuParentid": "3197bf2e-79a3-4203-b907-ddd953becb38",
        "menuLinkurl": "../frames/auth/logManager/index.html",
        "menuOtherparam": null,
        "menuLinktarget": "Tab",
        "menuType": "链接",
        "menuIsdefault": "是",
        "menuIsmodify": "启用",
        "menuPos": null,
        "menuCreateby": "admin",
        "menuCreatetime": 1539898354000,
        "menuSortnum": 60,
        "menuNote": null,
        "menuLinkname": null
      },
      {
        "menuId": "374a9d75-7350-4440-8b3a-76f02775aa52",
        "menuIcourl": "iconfont icon-auz",
        "menuText": "系统授权管理",
        "menuParentid": "3197bf2e-79a3-4203-b907-ddd953becb38",
        "menuLinkurl": "pageId=PE8525E594A224D34BC0024A02AE16EE6",
        "menuOtherparam": "PE8525E594A224D34BC0024A02AE16EE6",
        "menuLinktarget": "Tab",
        "menuType": "链接",
        "menuIsdefault": "是",
        "menuIsmodify": "启用",
        "menuPos": "左侧",
        "menuCreateby": "47d50142-2ca9-47cc-ac49-7a6c3e4625c1",
        "menuCreatetime": 1558702046000,
        "menuSortnum": 100,
        "menuNote": null,
        "menuLinkname": null
      },
      {
        "menuId": "83f13ee2-ada6-40f8-8ec4-c6aee02c01b9",
        "menuIcourl": "iconfont icon-yonghu",
        "menuText": "个人信息设置",
        "menuParentid": "3197bf2e-79a3-4203-b907-ddd953becb38",
        "menuLinkurl": "pageId=P30FEC65425924D0897BE0D9AD22C359C",
        "menuOtherparam": "P30FEC65425924D0897BE0D9AD22C359C",
        "menuLinktarget": "Tab",
        "menuType": "链接",
        "menuIsdefault": "是",
        "menuIsmodify": "启用",
        "menuPos": "左侧",
        "menuCreateby": "dde28e2a-f6ec-48c6-8570-32dd4aab4751",
        "menuCreatetime": 1568694342000,
        "menuSortnum": 100,
        "menuNote": null,
        "menuLinkname": null
      },
      {
        "menuId": "150d2484-eff6-4b72-8fe8-288aabf7e204",
        "menuIcourl": "iconfont icon-team",
        "menuText": "自定义分组管理",
        "menuParentid": "3197bf2e-79a3-4203-b907-ddd953becb38",
        "menuLinkurl": "../frames/msg/IM/imSelfGroupManage/index.html",
        "menuOtherparam": null,
        "menuLinktarget": "Tab",
        "menuType": "链接",
        "menuIsdefault": "是",
        "menuIsmodify": "启用",
        "menuPos": null,
        "menuCreateby": "4bdae713-6f5c-4513-957d-3f2566f6f495",
        "menuCreatetime": 1572974552000,
        "menuSortnum": 110,
        "menuNote": null,
        "menuLinkname": null
      },
      {
        "menuId": "d9541599-72ba-457c-af88-fe51a43af3a4",
        "menuIcourl": "iconfont icon-xiaoxi",
        "menuText": "消息中心",
        "menuParentid": "",
        "menuLinkurl": null,
        "menuOtherparam": null,
        "menuLinktarget": "Tab",
        "menuType": "菜单",
        "menuIsdefault": "是",
        "menuIsmodify": "启用",
        "menuPos": null,
        "menuCreateby": "admin",
        "menuCreatetime": 1534967945000,
        "menuSortnum": 50,
        "menuNote": null,
        "menuLinkname": null
      },
      {
        "menuId": "d44b0078-d018-476a-a048-85d825e2c55a",
        "menuIcourl": "iconfont icon-message-template",
        "menuText": "消息模板配置",
        "menuParentid": "d9541599-72ba-457c-af88-fe51a43af3a4",
        "menuLinkurl": "../frames/msg/configMgr/configMsg/index.html",
        "menuOtherparam": null,
        "menuLinktarget": "Tab",
        "menuType": "链接",
        "menuIsdefault": "是",
        "menuIsmodify": "启用",
        "menuPos": null,
        "menuCreateby": "admin",
        "menuCreatetime": 1534992343000,
        "menuSortnum": 5,
        "menuNote": null,
        "menuLinkname": null
      },
      {
        "menuId": "390d0f9a-26bb-47f2-ab66-859a748aac6c",
        "menuIcourl": "iconfont icon-message-configuration",
        "menuText": "外部消息配置",
        "menuParentid": "d9541599-72ba-457c-af88-fe51a43af3a4",
        "menuLinkurl": "../frames/msg/configMgr/configSms/index.html",
        "menuOtherparam": null,
        "menuLinktarget": "Tab",
        "menuType": "链接",
        "menuIsdefault": "是",
        "menuIsmodify": "启用",
        "menuPos": null,
        "menuCreateby": "admin",
        "menuCreatetime": 1534992416000,
        "menuSortnum": 6,
        "menuNote": null,
        "menuLinkname": null
      },
      {
        "menuId": "5fed3876-02fb-4e93-95f9-35b1db2371ff",
        "menuIcourl": "iconfont icon-personal-news",
        "menuText": "个人消息",
        "menuParentid": "d9541599-72ba-457c-af88-fe51a43af3a4",
        "menuLinkurl": "../frames/msg/configMgr/personalMsg/index.html",
        "menuOtherparam": null,
        "menuLinktarget": "Tab",
        "menuType": "链接",
        "menuIsdefault": "是",
        "menuIsmodify": "启用",
        "menuPos": null,
        "menuCreateby": "admin",
        "menuCreatetime": 1535140495000,
        "menuSortnum": 7,
        "menuNote": null,
        "menuLinkname": null
      },
      {
        "menuId": "2fc552ef-c5af-48e7-b2e6-4bc0054b5fd8",
        "menuIcourl": "iconfont icon-task",
        "menuText": "我的日程",
        "menuParentid": "d9541599-72ba-457c-af88-fe51a43af3a4",
        "menuLinkurl": "../frames/msg/schedule/index.html",
        "menuOtherparam": null,
        "menuLinktarget": "Tab",
        "menuType": "链接",
        "menuIsdefault": "是",
        "menuIsmodify": "启用",
        "menuPos": null,
        "menuCreateby": "admin",
        "menuCreatetime": 1535256706000,
        "menuSortnum": 8,
        "menuNote": null,
        "menuLinkname": null
      },
      {
        "menuId": "1ee475fb-80a9-47c6-8f1c-a4c5fc1062be",
        "menuIcourl": "iconfont icon-mail-unread",
        "menuText": "邮件管理",
        "menuParentid": "d9541599-72ba-457c-af88-fe51a43af3a4",
        "menuLinkurl": null,
        "menuOtherparam": null,
        "menuLinktarget": "Tab",
        "menuType": "菜单",
        "menuIsdefault": "是",
        "menuIsmodify": "启用",
        "menuPos": "左侧",
        "menuCreateby": null,
        "menuCreatetime": 1527016534000,
        "menuSortnum": 10,
        "menuNote": "邮件管理",
        "menuLinkname": null
      },
      {
        "menuId": "be7d3df9-5635-400d-9c53-638e357afc64",
        "menuIcourl": "iconfont icon-edit",
        "menuText": "写邮件",
        "menuParentid": "1ee475fb-80a9-47c6-8f1c-a4c5fc1062be",
        "menuLinkurl": "../frames/msg/mail/send/index.html?type=1",
        "menuOtherparam": null,
        "menuLinktarget": "Tab",
        "menuType": "链接",
        "menuIsdefault": "否",
        "menuIsmodify": "启用",
        "menuPos": "左侧",
        "menuCreateby": null,
        "menuCreatetime": 1527016577000,
        "menuSortnum": 1,
        "menuNote": "发邮件",
        "menuLinkname": null
      },
      {
        "menuId": "a0a990c3-b7d6-455a-9dfa-a234fcbc8151",
        "menuIcourl": "iconfont icon-receive-mail",
        "menuText": "收件箱",
        "menuParentid": "1ee475fb-80a9-47c6-8f1c-a4c5fc1062be",
        "menuLinkurl": "../frames/msg/mail/inbox/index.html?type=2",
        "menuOtherparam": null,
        "menuLinktarget": "Tab",
        "menuType": "链接",
        "menuIsdefault": "否",
        "menuIsmodify": "启用",
        "menuPos": "左侧",
        "menuCreateby": null,
        "menuCreatetime": 1527016639000,
        "menuSortnum": 1,
        "menuNote": "收邮件 type===2",
        "menuLinkname": null
      },
      {
        "menuId": "0ec6f9d9-a7fb-4ac6-9edd-5f3881b6ed36",
        "menuIcourl": "iconfont icon-post-mail",
        "menuText": "发件箱",
        "menuParentid": "1ee475fb-80a9-47c6-8f1c-a4c5fc1062be",
        "menuLinkurl": "../frames/msg/mail/inbox/index.html?type=1",
        "menuOtherparam": null,
        "menuLinktarget": "Tab",
        "menuType": "链接",
        "menuIsdefault": "是",
        "menuIsmodify": "启用",
        "menuPos": null,
        "menuCreateby": "admin",
        "menuCreatetime": 1535140982000,
        "menuSortnum": 1,
        "menuNote": "发邮件 type===1",
        "menuLinkname": null
      },
      {
        "menuId": "d74fbd3d-1016-4fcf-8f79-91d37eedfe00",
        "menuIcourl": "iconfont icon-business-management",
        "menuText": "草稿箱",
        "menuParentid": "1ee475fb-80a9-47c6-8f1c-a4c5fc1062be",
        "menuLinkurl": "../frames/msg/mail/inbox/index.html?type=0",
        "menuOtherparam": null,
        "menuLinktarget": "Tab",
        "menuType": "链接",
        "menuIsdefault": "是",
        "menuIsmodify": "启用",
        "menuPos": null,
        "menuCreateby": "admin",
        "menuCreatetime": 1535261478000,
        "menuSortnum": 1,
        "menuNote": "草稿箱 type===0",
        "menuLinkname": null
      },
      {
        "menuId": "f9c891f2-31ff-4a35-a6b0-2eb0b19f91ee",
        "menuIcourl": "iconfont icon-star1",
        "menuText": "收藏夹",
        "menuParentid": "1ee475fb-80a9-47c6-8f1c-a4c5fc1062be",
        "menuLinkurl": "../frames/msg/mail/inbox/index.html?type=3",
        "menuOtherparam": null,
        "menuLinktarget": "Tab",
        "menuType": "链接",
        "menuIsdefault": "是",
        "menuIsmodify": "启用",
        "menuPos": null,
        "menuCreateby": "admin",
        "menuCreatetime": 1535261494000,
        "menuSortnum": 1,
        "menuNote": null,
        "menuLinkname": null
      },
      {
        "menuId": "663ba5da-2cdf-413e-97b6-6acd5094a27a",
        "menuIcourl": "iconfont icon-dustbin",
        "menuText": "垃圾箱",
        "menuParentid": "1ee475fb-80a9-47c6-8f1c-a4c5fc1062be",
        "menuLinkurl": "../frames/msg/mail/inbox/index.html?type=4",
        "menuOtherparam": null,
        "menuLinktarget": "Tab",
        "menuType": "链接",
        "menuIsdefault": "是",
        "menuIsmodify": "启用",
        "menuPos": null,
        "menuCreateby": "admin",
        "menuCreatetime": 1535261504000,
        "menuSortnum": 1,
        "menuNote": null,
        "menuLinkname": null
      },
      {
        "menuId": "5c45764a-6df7-46c2-923f-166aee84b6a7",
        "menuIcourl": "iconfont icon-reply-fill",
        "menuText": "短信管理",
        "menuParentid": "d9541599-72ba-457c-af88-fe51a43af3a4",
        "menuLinkurl": null,
        "menuOtherparam": null,
        "menuLinktarget": "Tab",
        "menuType": "菜单",
        "menuIsdefault": "否",
        "menuIsmodify": "启用",
        "menuPos": "左侧",
        "menuCreateby": null,
        "menuCreatetime": 1527016837000,
        "menuSortnum": 10,
        "menuNote": "短信管理",
        "menuLinkname": null
      },
      {
        "menuId": "b4f75311-5ce4-4545-82a4-3afc04544622",
        "menuIcourl": "iconfont icon-directory",
        "menuText": "通讯录",
        "menuParentid": "5c45764a-6df7-46c2-923f-166aee84b6a7",
        "menuLinkurl": "../frames/msg/sms/contactList/index.html",
        "menuOtherparam": null,
        "menuLinktarget": "Tab",
        "menuType": "链接",
        "menuIsdefault": "是",
        "menuIsmodify": "启用",
        "menuPos": "左侧",
        "menuCreateby": null,
        "menuCreatetime": 1527016903000,
        "menuSortnum": 1,
        "menuNote": "通讯录",
        "menuLinkname": null
      },
      {
        "menuId": "65b98350-7325-4439-8ceb-c8c8956d8d7d",
        "menuIcourl": "iconfont icon-general-o",
        "menuText": "发短信",
        "menuParentid": "5c45764a-6df7-46c2-923f-166aee84b6a7",
        "menuLinkurl": "../frames/msg/sms/send/index.html",
        "menuOtherparam": null,
        "menuLinktarget": "Tab",
        "menuType": "链接",
        "menuIsdefault": "是",
        "menuIsmodify": "启用",
        "menuPos": "左侧",
        "menuCreateby": null,
        "menuCreatetime": 1527016958000,
        "menuSortnum": 2,
        "menuNote": null,
        "menuLinkname": null
      },
      {
        "menuId": "632bece9-3d81-4c58-bf2f-5ebc11c1b63f",
        "menuIcourl": "iconfont icon-business-management",
        "menuText": "草稿箱",
        "menuParentid": "5c45764a-6df7-46c2-923f-166aee84b6a7",
        "menuLinkurl": "../frames/msg/sms/outbox/index.html?type=0",
        "menuOtherparam": null,
        "menuLinktarget": "Tab",
        "menuType": "链接",
        "menuIsdefault": "是",
        "menuIsmodify": "启用",
        "menuPos": "左侧",
        "menuCreateby": null,
        "menuCreatetime": 1527017017000,
        "menuSortnum": 3,
        "menuNote": null,
        "menuLinkname": null
      },
      {
        "menuId": "7366b583-c4f7-469c-a425-0344e1d7c0e6",
        "menuIcourl": "iconfont icon-mail-o",
        "menuText": "发信箱",
        "menuParentid": "5c45764a-6df7-46c2-923f-166aee84b6a7",
        "menuLinkurl": "../frames/msg/sms/outbox/index.html?type=1",
        "menuOtherparam": null,
        "menuLinktarget": "Tab",
        "menuType": "链接",
        "menuIsdefault": "是",
        "menuIsmodify": "启用",
        "menuPos": null,
        "menuCreateby": "admin",
        "menuCreatetime": 1535261638000,
        "menuSortnum": 4,
        "menuNote": null,
        "menuLinkname": null
      },
      {
        "menuId": "0ddbed16-a7a7-49d3-ac28-5664f7e75203",
        "menuIcourl": "iconfont icon-common-language",
        "menuText": "常用语",
        "menuParentid": "5c45764a-6df7-46c2-923f-166aee84b6a7",
        "menuLinkurl": "../frames/msg/sms/phrasebook/index.html",
        "menuOtherparam": null,
        "menuLinktarget": "Tab",
        "menuType": "链接",
        "menuIsdefault": "是",
        "menuIsmodify": "启用",
        "menuPos": null,
        "menuCreateby": "admin",
        "menuCreatetime": 1535261711000,
        "menuSortnum": 5,
        "menuNote": null,
        "menuLinkname": null
      },
      {
        "menuId": "59d77b86-4a4d-458c-ab31-fc4217a71e8b",
        "menuIcourl": "iconfont icon-schedule-o",
        "menuText": "短信日志",
        "menuParentid": "5c45764a-6df7-46c2-923f-166aee84b6a7",
        "menuLinkurl": "../frames/msg/sms/smsLog/index.html",
        "menuOtherparam": null,
        "menuLinktarget": "Tab",
        "menuType": "链接",
        "menuIsdefault": "是",
        "menuIsmodify": "启用",
        "menuPos": null,
        "menuCreateby": "admin",
        "menuCreatetime": 1535261721000,
        "menuSortnum": 6,
        "menuNote": null,
        "menuLinkname": null
      },
      {
        "menuId": "50cb03fc-1360-4dd5-8c28-16bffd03f4d7",
        "menuIcourl": "iconfont icon-notice-announcement",
        "menuText": "通知公告",
        "menuParentid": "d9541599-72ba-457c-af88-fe51a43af3a4",
        "menuLinkurl": null,
        "menuOtherparam": null,
        "menuLinktarget": "Tab",
        "menuType": "菜单",
        "menuIsdefault": "是",
        "menuIsmodify": "启用",
        "menuPos": null,
        "menuCreateby": "admin",
        "menuCreatetime": 1535140715000,
        "menuSortnum": 10,
        "menuNote": null,
        "menuLinkname": null
      },
      {
        "menuId": "53384f17-a4db-49d5-8d4f-f8c95dc8877e",
        "menuIcourl": "iconfont icon-announcement-query-fill",
        "menuText": "公告查询",
        "menuParentid": "50cb03fc-1360-4dd5-8c28-16bffd03f4d7",
        "menuLinkurl": "../frames/msg/notify/notifyQuery/index.html",
        "menuOtherparam": null,
        "menuLinktarget": "Tab",
        "menuType": "链接",
        "menuIsdefault": "是",
        "menuIsmodify": "启用",
        "menuPos": null,
        "menuCreateby": "admin",
        "menuCreatetime": 1535261756000,
        "menuSortnum": 3,
        "menuNote": null,
        "menuLinkname": null
      },
      {
        "menuId": "3f70a865-8708-49a7-b203-c3739e8aacc9",
        "menuIcourl": "iconfont icon-meeting",
        "menuText": "公告发布",
        "menuParentid": "50cb03fc-1360-4dd5-8c28-16bffd03f4d7",
        "menuLinkurl": "../frames/msg/notify/notifyIssued/index.html",
        "menuOtherparam": null,
        "menuLinktarget": "Tab",
        "menuType": "链接",
        "menuIsdefault": "是",
        "menuIsmodify": "启用",
        "menuPos": null,
        "menuCreateby": "admin",
        "menuCreatetime": 1535261745000,
        "menuSortnum": 4,
        "menuNote": null,
        "menuLinkname": null
      },
      {
        "menuId": "6867d64d-414f-45e6-8d14-1cd47cc56b46",
        "menuIcourl": "iconfont icon-announcement",
        "menuText": "公告管理",
        "menuParentid": "50cb03fc-1360-4dd5-8c28-16bffd03f4d7",
        "menuLinkurl": "../frames/msg/notify/notifyMgr/index.html",
        "menuOtherparam": null,
        "menuLinktarget": "Tab",
        "menuType": "链接",
        "menuIsdefault": "是",
        "menuIsmodify": "启用",
        "menuPos": null,
        "menuCreateby": "admin",
        "menuCreatetime": 1535261767000,
        "menuSortnum": 5,
        "menuNote": null,
        "menuLinkname": null
      },
      {
        "menuId": "7034008c-06c3-401c-9ed5-55576402fb15",
        "menuIcourl": "iconfont icon-template2",
        "menuText": "公告类型管理",
        "menuParentid": "50cb03fc-1360-4dd5-8c28-16bffd03f4d7",
        "menuLinkurl": "../frames/msg/notify/notifyType/index.html",
        "menuOtherparam": null,
        "menuLinktarget": "Tab",
        "menuType": "链接",
        "menuIsdefault": "是",
        "menuIsmodify": "启用",
        "menuPos": null,
        "menuCreateby": "admin",
        "menuCreatetime": 1535261784000,
        "menuSortnum": 6,
        "menuNote": null,
        "menuLinkname": null
      }
    ]
  }
  